package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.Follow;
import pojo.FollowExample;
import pojo.FollowKey;

public interface FollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int countByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int deleteByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int deleteByPrimaryKey(FollowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int insert(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int insertSelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    List<Follow> selectByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    Follow selectByPrimaryKey(FollowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Follow record, @Param("example") FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int updateByExample(@Param("record") Follow record, @Param("example") FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int updateByPrimaryKeySelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int updateByPrimaryKey(Follow record);
}