package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.Interact;
import pojo.InteractExample;

public interface InteractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int countByExample(InteractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int deleteByExample(InteractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int deleteByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int insert(Interact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int insertSelective(Interact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    List<Interact> selectByExample(InteractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    Interact selectByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Interact record, @Param("example") InteractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int updateByExample(@Param("record") Interact record, @Param("example") InteractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int updateByPrimaryKeySelective(Interact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interact
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    int updateByPrimaryKey(Interact record);
}