package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.Share;
import pojo.ShareExample;
import pojo.ShareKey;

public interface ShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    int countByExample(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    int deleteByExample(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    int deleteByPrimaryKey(ShareKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    int insert(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    int insertSelective(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    List<Share> selectByExample(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    Share selectByPrimaryKey(ShareKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Share record, @Param("example") ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    int updateByExample(@Param("record") Share record, @Param("example") ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    int updateByPrimaryKeySelective(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    int updateByPrimaryKey(Share record);
}