package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.TagWorkExample;
import pojo.TagWorkKey;

public interface TagWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_work
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int countByExample(TagWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_work
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int deleteByExample(TagWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_work
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int deleteByPrimaryKey(TagWorkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_work
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int insert(TagWorkKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_work
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int insertSelective(TagWorkKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_work
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    List<TagWorkKey> selectByExample(TagWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_work
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") TagWorkKey record, @Param("example") TagWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_work
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByExample(@Param("record") TagWorkKey record, @Param("example") TagWorkExample example);
}