package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.WorkContent;
import pojo.WorkContentExample;

public interface WorkContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int countByExample(WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int deleteByExample(WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int deleteByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int insert(WorkContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int insertSelective(WorkContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    List<WorkContent> selectByExampleWithBLOBs(WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    List<WorkContent> selectByExample(WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    WorkContent selectByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkContent record, @Param("example") WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") WorkContent record, @Param("example") WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByExample(@Param("record") WorkContent record, @Param("example") WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByPrimaryKeySelective(WorkContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(WorkContent record);
}