package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.WorkInfo;
import pojo.WorkInfoExample;

public interface WorkInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int countByExample(WorkInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int deleteByExample(WorkInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int deleteByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int insert(WorkInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int insertSelective(WorkInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    List<WorkInfo> selectByExample(WorkInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    WorkInfo selectByPrimaryKey(Integer workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkInfo record, @Param("example") WorkInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByExample(@Param("record") WorkInfo record, @Param("example") WorkInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByPrimaryKeySelective(WorkInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    int updateByPrimaryKey(WorkInfo record);
}