package pojo;

import org.springframework.stereotype.Component;

@Component
public class About {
     /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about.about_user_id
     *
     * @mbggenerated Thu Jan 04 16:58:35 CST 2018
     */
    private String aboutUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about.about_content_markdown
     *
     * @mbggenerated Thu Jan 04 16:58:35 CST 2018
     */
    private String aboutContentMarkdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about.about_content_html
     *
     * @mbggenerated Thu Jan 04 16:58:35 CST 2018
     */
    private String aboutContentHtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about.about_user_id
     *
     * @return the value of about.about_user_id
     *
     * @mbggenerated Thu Jan 04 16:58:35 CST 2018
     */
    public String getAboutUserId() {
        return aboutUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about.about_user_id
     *
     * @param aboutUserId the value for about.about_user_id
     *
     * @mbggenerated Thu Jan 04 16:58:35 CST 2018
     */
    public void setAboutUserId(String aboutUserId) {
        this.aboutUserId = aboutUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about.about_content_markdown
     *
     * @return the value of about.about_content_markdown
     *
     * @mbggenerated Thu Jan 04 16:58:35 CST 2018
     */
    public String getAboutContentMarkdown() {
        return aboutContentMarkdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about.about_content_markdown
     *
     * @param aboutContentMarkdown the value for about.about_content_markdown
     *
     * @mbggenerated Thu Jan 04 16:58:35 CST 2018
     */
    public void setAboutContentMarkdown(String aboutContentMarkdown) {
        this.aboutContentMarkdown = aboutContentMarkdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about.about_content_html
     *
     * @return the value of about.about_content_html
     *
     * @mbggenerated Thu Jan 04 16:58:35 CST 2018
     */
    public String getAboutContentHtml() {
        return aboutContentHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about.about_content_html
     *
     * @param aboutContentHtml the value for about.about_content_html
     *
     * @mbggenerated Thu Jan 04 16:58:35 CST 2018
     */
    public void setAboutContentHtml(String aboutContentHtml) {
        this.aboutContentHtml = aboutContentHtml;
    }
}