package pojo;

public class About {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about.about_user_id
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    private String aboutUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about.about_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    private String aboutContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about.about_user_id
     *
     * @return the value of about.about_user_id
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public String getAboutUserId() {
        return aboutUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about.about_user_id
     *
     * @param aboutUserId the value for about.about_user_id
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public void setAboutUserId(String aboutUserId) {
        this.aboutUserId = aboutUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about.about_content
     *
     * @return the value of about.about_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public String getAboutContent() {
        return aboutContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about.about_content
     *
     * @param aboutContent the value for about.about_content
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public void setAboutContent(String aboutContent) {
        this.aboutContent = aboutContent;
    }
}