package pojo;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.Date;
@Component
@Scope("prototype")
public class Follow extends FollowKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.follow_time
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private Date followTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.follow_time
     *
     * @return the value of follow.follow_time
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public Date getFollowTime() {
        return followTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.follow_time
     *
     * @param followTime the value for follow.follow_time
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setFollowTime(Date followTime) {
        this.followTime = followTime;
    }
}