package pojo;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.Date;
@Component
@Scope("prototype")
public class Interact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.act_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private Integer actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.to_act_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private Integer toActId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.actor_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private String actorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.act_type
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private String actType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.to_actor_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private String toActorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.to_work_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private Integer toWorkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.act_content
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private String actContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.to_act_content
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private String toActContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.act_generate_time
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private Date actGenerateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interact.act_is_read
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    private Boolean actIsRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.act_id
     *
     * @return the value of interact.act_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public Integer getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.act_id
     *
     * @param actId the value for interact.act_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setActId(Integer actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.to_act_id
     *
     * @return the value of interact.to_act_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public Integer getToActId() {
        return toActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.to_act_id
     *
     * @param toActId the value for interact.to_act_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setToActId(Integer toActId) {
        this.toActId = toActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.actor_id
     *
     * @return the value of interact.actor_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public String getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.actor_id
     *
     * @param actorId the value for interact.actor_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setActorId(String actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.act_type
     *
     * @return the value of interact.act_type
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public String getActType() {
        return actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.act_type
     *
     * @param actType the value for interact.act_type
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setActType(String actType) {
        this.actType = actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.to_actor_id
     *
     * @return the value of interact.to_actor_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public String getToActorId() {
        return toActorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.to_actor_id
     *
     * @param toActorId the value for interact.to_actor_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setToActorId(String toActorId) {
        this.toActorId = toActorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.to_work_id
     *
     * @return the value of interact.to_work_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public Integer getToWorkId() {
        return toWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.to_work_id
     *
     * @param toWorkId the value for interact.to_work_id
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setToWorkId(Integer toWorkId) {
        this.toWorkId = toWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.act_content
     *
     * @return the value of interact.act_content
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public String getActContent() {
        return actContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.act_content
     *
     * @param actContent the value for interact.act_content
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setActContent(String actContent) {
        this.actContent = actContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.to_act_content
     *
     * @return the value of interact.to_act_content
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public String getToActContent() {
        return toActContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.to_act_content
     *
     * @param toActContent the value for interact.to_act_content
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setToActContent(String toActContent) {
        this.toActContent = toActContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.act_generate_time
     *
     * @return the value of interact.act_generate_time
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public Date getActGenerateTime() {
        return actGenerateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.act_generate_time
     *
     * @param actGenerateTime the value for interact.act_generate_time
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setActGenerateTime(Date actGenerateTime) {
        this.actGenerateTime = actGenerateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interact.act_is_read
     *
     * @return the value of interact.act_is_read
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public Boolean getActIsRead() {
        return actIsRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interact.act_is_read
     *
     * @param actIsRead the value for interact.act_is_read
     *
     * @mbggenerated Wed May 09 11:39:51 CST 2018
     */
    public void setActIsRead(Boolean actIsRead) {
        this.actIsRead = actIsRead;
    }
}