package pojo;

public class ShareKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.userId
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.workId
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    private Integer workid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.userId
     *
     * @return the value of share.userId
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.userId
     *
     * @param userid the value for share.userId
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.workId
     *
     * @return the value of share.workId
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    public Integer getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.workId
     *
     * @param workid the value for share.workId
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    public void setWorkid(Integer workid) {
        this.workid = workid;
    }
}