package pojo;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.Date;
@Component
@Scope("prototype")
public class Share extends ShareKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.share_time
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    private Date shareTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.share_time
     *
     * @return the value of share.share_time
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    public Date getShareTime() {
        return shareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.share_time
     *
     * @param shareTime the value for share.share_time
     *
     * @mbggenerated Tue May 08 09:02:09 CST 2018
     */
    public void setShareTime(Date shareTime) {
        this.shareTime = shareTime;
    }
}