package pojo;

public class TagWorkKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_work.tag_name
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_work.work_id
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    private Integer workId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_work.tag_name
     *
     * @return the value of tag_work.tag_name
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_work.tag_name
     *
     * @param tagName the value for tag_work.tag_name
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_work.work_id
     *
     * @return the value of tag_work.work_id
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_work.work_id
     *
     * @param workId the value for tag_work.work_id
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }
}