package pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_headicon_path
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    private String userHeadiconPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_introduction
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    private String userIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_register_time
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    private Date userRegisterTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_headicon_path
     *
     * @return the value of user.user_headicon_path
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public String getUserHeadiconPath() {
        return userHeadiconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_headicon_path
     *
     * @param userHeadiconPath the value for user.user_headicon_path
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public void setUserHeadiconPath(String userHeadiconPath) {
        this.userHeadiconPath = userHeadiconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_introduction
     *
     * @return the value of user.user_introduction
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public String getUserIntroduction() {
        return userIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_introduction
     *
     * @param userIntroduction the value for user.user_introduction
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public void setUserIntroduction(String userIntroduction) {
        this.userIntroduction = userIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_register_time
     *
     * @return the value of user.user_register_time
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public Date getUserRegisterTime() {
        return userRegisterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_register_time
     *
     * @param userRegisterTime the value for user.user_register_time
     *
     * @mbggenerated Fri Dec 29 09:40:40 CST 2017
     */
    public void setUserRegisterTime(Date userRegisterTime) {
        this.userRegisterTime = userRegisterTime;
    }
}