package pojo;

import org.springframework.stereotype.Component;

@Component
public class WorkContent {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_content.work_id
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    private Integer workId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_content.work_content_markdown
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    private String workContentMarkdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_content.work_content_html
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    private String workContentHtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_content.work_id
     *
     * @return the value of work_content.work_id
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_content.work_id
     *
     * @param workId the value for work_content.work_id
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_content.work_content_markdown
     *
     * @return the value of work_content.work_content_markdown
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public String getWorkContentMarkdown() {
        return workContentMarkdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_content.work_content_markdown
     *
     * @param workContentMarkdown the value for work_content.work_content_markdown
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public void setWorkContentMarkdown(String workContentMarkdown) {
        this.workContentMarkdown = workContentMarkdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_content.work_content_html
     *
     * @return the value of work_content.work_content_html
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public String getWorkContentHtml() {
        return workContentHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_content.work_content_html
     *
     * @param workContentHtml the value for work_content.work_content_html
     *
     * @mbggenerated Thu Jan 04 10:41:16 CST 2018
     */
    public void setWorkContentHtml(String workContentHtml) {
        this.workContentHtml = workContentHtml;
    }
}