package pojo;

import org.springframework.stereotype.Component;

import java.util.Date;
@Component
public class WorkInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_info.work_id
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    private Integer workId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_info.work_user_id
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    private String workUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_info.work_generates_time
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    private Date workGeneratesTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_info.work_category
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    private String workCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_info.work_browse_sum
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    private Integer workBrowseSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_info.work_title
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    private String workTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_info.work_id
     *
     * @return the value of work_info.work_id
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_info.work_id
     *
     * @param workId the value for work_info.work_id
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_info.work_user_id
     *
     * @return the value of work_info.work_user_id
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public String getWorkUserId() {
        return workUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_info.work_user_id
     *
     * @param workUserId the value for work_info.work_user_id
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void setWorkUserId(String workUserId) {
        this.workUserId = workUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_info.work_generates_time
     *
     * @return the value of work_info.work_generates_time
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public Date getWorkGeneratesTime() {
        return workGeneratesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_info.work_generates_time
     *
     * @param workGeneratesTime the value for work_info.work_generates_time
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void setWorkGeneratesTime(Date workGeneratesTime) {
        this.workGeneratesTime = workGeneratesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_info.work_category
     *
     * @return the value of work_info.work_category
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public String getWorkCategory() {
        return workCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_info.work_category
     *
     * @param workCategory the value for work_info.work_category
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void setWorkCategory(String workCategory) {
        this.workCategory = workCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_info.work_browse_sum
     *
     * @return the value of work_info.work_browse_sum
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public Integer getWorkBrowseSum() {
        return workBrowseSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_info.work_browse_sum
     *
     * @param workBrowseSum the value for work_info.work_browse_sum
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void setWorkBrowseSum(Integer workBrowseSum) {
        this.workBrowseSum = workBrowseSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_info.work_title
     *
     * @return the value of work_info.work_title
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public String getWorkTitle() {
        return workTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_info.work_title
     *
     * @param workTitle the value for work_info.work_title
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void setWorkTitle(String workTitle) {
        this.workTitle = workTitle;
    }
}