package pojo;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
@Component
@Scope("prototype")
public class WorkInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public WorkInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWorkIdIsNull() {
            addCriterion("work_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkIdIsNotNull() {
            addCriterion("work_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkIdEqualTo(Integer value) {
            addCriterion("work_id =", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdNotEqualTo(Integer value) {
            addCriterion("work_id <>", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdGreaterThan(Integer value) {
            addCriterion("work_id >", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("work_id >=", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdLessThan(Integer value) {
            addCriterion("work_id <", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdLessThanOrEqualTo(Integer value) {
            addCriterion("work_id <=", value, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdIn(List<Integer> values) {
            addCriterion("work_id in", values, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdNotIn(List<Integer> values) {
            addCriterion("work_id not in", values, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdBetween(Integer value1, Integer value2) {
            addCriterion("work_id between", value1, value2, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("work_id not between", value1, value2, "workId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdIsNull() {
            addCriterion("work_user_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdIsNotNull() {
            addCriterion("work_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdEqualTo(String value) {
            addCriterion("work_user_id =", value, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdNotEqualTo(String value) {
            addCriterion("work_user_id <>", value, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdGreaterThan(String value) {
            addCriterion("work_user_id >", value, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("work_user_id >=", value, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdLessThan(String value) {
            addCriterion("work_user_id <", value, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdLessThanOrEqualTo(String value) {
            addCriterion("work_user_id <=", value, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdLike(String value) {
            addCriterion("work_user_id like", value, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdNotLike(String value) {
            addCriterion("work_user_id not like", value, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdIn(List<String> values) {
            addCriterion("work_user_id in", values, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdNotIn(List<String> values) {
            addCriterion("work_user_id not in", values, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdBetween(String value1, String value2) {
            addCriterion("work_user_id between", value1, value2, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkUserIdNotBetween(String value1, String value2) {
            addCriterion("work_user_id not between", value1, value2, "workUserId");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeIsNull() {
            addCriterion("work_generates_time is null");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeIsNotNull() {
            addCriterion("work_generates_time is not null");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeEqualTo(Date value) {
            addCriterion("work_generates_time =", value, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeNotEqualTo(Date value) {
            addCriterion("work_generates_time <>", value, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeGreaterThan(Date value) {
            addCriterion("work_generates_time >", value, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("work_generates_time >=", value, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeLessThan(Date value) {
            addCriterion("work_generates_time <", value, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeLessThanOrEqualTo(Date value) {
            addCriterion("work_generates_time <=", value, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeIn(List<Date> values) {
            addCriterion("work_generates_time in", values, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeNotIn(List<Date> values) {
            addCriterion("work_generates_time not in", values, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeBetween(Date value1, Date value2) {
            addCriterion("work_generates_time between", value1, value2, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkGeneratesTimeNotBetween(Date value1, Date value2) {
            addCriterion("work_generates_time not between", value1, value2, "workGeneratesTime");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryIsNull() {
            addCriterion("work_category is null");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryIsNotNull() {
            addCriterion("work_category is not null");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryEqualTo(String value) {
            addCriterion("work_category =", value, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryNotEqualTo(String value) {
            addCriterion("work_category <>", value, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryGreaterThan(String value) {
            addCriterion("work_category >", value, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("work_category >=", value, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryLessThan(String value) {
            addCriterion("work_category <", value, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryLessThanOrEqualTo(String value) {
            addCriterion("work_category <=", value, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryLike(String value) {
            addCriterion("work_category like", value, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryNotLike(String value) {
            addCriterion("work_category not like", value, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryIn(List<String> values) {
            addCriterion("work_category in", values, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryNotIn(List<String> values) {
            addCriterion("work_category not in", values, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryBetween(String value1, String value2) {
            addCriterion("work_category between", value1, value2, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkCategoryNotBetween(String value1, String value2) {
            addCriterion("work_category not between", value1, value2, "workCategory");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumIsNull() {
            addCriterion("work_browse_sum is null");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumIsNotNull() {
            addCriterion("work_browse_sum is not null");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumEqualTo(Integer value) {
            addCriterion("work_browse_sum =", value, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumNotEqualTo(Integer value) {
            addCriterion("work_browse_sum <>", value, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumGreaterThan(Integer value) {
            addCriterion("work_browse_sum >", value, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumGreaterThanOrEqualTo(Integer value) {
            addCriterion("work_browse_sum >=", value, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumLessThan(Integer value) {
            addCriterion("work_browse_sum <", value, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumLessThanOrEqualTo(Integer value) {
            addCriterion("work_browse_sum <=", value, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumIn(List<Integer> values) {
            addCriterion("work_browse_sum in", values, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumNotIn(List<Integer> values) {
            addCriterion("work_browse_sum not in", values, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumBetween(Integer value1, Integer value2) {
            addCriterion("work_browse_sum between", value1, value2, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkBrowseSumNotBetween(Integer value1, Integer value2) {
            addCriterion("work_browse_sum not between", value1, value2, "workBrowseSum");
            return (Criteria) this;
        }

        public Criteria andWorkTitleIsNull() {
            addCriterion("work_title is null");
            return (Criteria) this;
        }

        public Criteria andWorkTitleIsNotNull() {
            addCriterion("work_title is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTitleEqualTo(String value) {
            addCriterion("work_title =", value, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleNotEqualTo(String value) {
            addCriterion("work_title <>", value, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleGreaterThan(String value) {
            addCriterion("work_title >", value, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleGreaterThanOrEqualTo(String value) {
            addCriterion("work_title >=", value, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleLessThan(String value) {
            addCriterion("work_title <", value, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleLessThanOrEqualTo(String value) {
            addCriterion("work_title <=", value, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleLike(String value) {
            addCriterion("work_title like", value, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleNotLike(String value) {
            addCriterion("work_title not like", value, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleIn(List<String> values) {
            addCriterion("work_title in", values, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleNotIn(List<String> values) {
            addCriterion("work_title not in", values, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleBetween(String value1, String value2) {
            addCriterion("work_title between", value1, value2, "workTitle");
            return (Criteria) this;
        }

        public Criteria andWorkTitleNotBetween(String value1, String value2) {
            addCriterion("work_title not between", value1, value2, "workTitle");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 05 15:34:58 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_info
     *
     * @mbggenerated Fri Jan 05 15:34:58 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}